trigger:
  - main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npx vite build
  displayName: 'Build React app with Vite'

- script: dir dist
  displayName: 'Check dist exists'
  continueOnError: true

- script: |
    echo "Listing root:"
    dir
    echo "Listing dist folder:"
    dir dist
  displayName: 'Debug folder structure'
  continueOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'vite-react-app'
    publishLocation: 'Container'
