trigger:
  - main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm run build
  displayName: 'Build React app with Vite'
  workingDirectory: '$(Build.SourcesDirectory)'

- script: |
    echo "Listing root:"
    dir
    echo "Listing dist folder:"
    dir dist
  displayName: 'Debug folder structure'
  continueOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'vite-react-app'
    publishLocation: 'Container'
